apiVersion: apps.kubermatic.k8c.io/v1
kind: ApplicationInstallation
metadata:
  name: nginx
  namespace: nginx
spec:
  applicationRef:
    name: nginx
    version: 1.12.0
  namespace:
    create: true
    name: nginx
  reconciliationInterval: 0s
  values: {}