apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
spec:
  selector:
    matchLabels:
      app: echo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
      - name: test
        image: ghcr.io/nicolaiort/kusatoko:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
          - name: ROOT_MESSAGE
            value: "Hello from gcp"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80