apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
spec:
  selector:
    matchLabels:
      app: echo-service
  replicas: 2
  template:
    metadata:
      labels:
        app: echo-service
    spec:
      containers:
      - name: test
        image: ghcr.io/nicolaiort/kusatoko:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
          - name: ROOT_MESSAGE
            value: "Hello from kubermatic (cluster3)"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: glsb-service
  name: glsb-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: echo-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glsb-service
  labels:
    app: glsb-service
spec:
  ingressClassName: nginx
  rules:
    - host: demo.k8gb.nig.gl
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: glsb-service
              port:
                number: 80