---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: meshed-service
  name: meshed-service
  annotations:
    io.cilium/global-service: "true"
    io.cilium/service-affinity: "local"
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: echo-service
