---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
  namespace: cert-manager
spec:
  acme:
    email: letsencrypt@nicolai-ort.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-dns-account-key
    solvers:
    - dns01:
        cloudflare:
          email: letsencrypt@nicolai-ort.com
          apiTokenSecretRef:
            name: letsencrypt-prod-dns-cloudflare-key
            key: token