---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: glsb-service
  name: glsb-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: echo-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: glsb-service
  labels:
    app: glsb-service
spec:
  ingressClassName: nginx
  rules:
    - host: demo.k8gb.nig.gl
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: glsb-service
              port:
                number: 80
---
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: glsb-service
spec:
  resourceRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    matchLabels:
      app: glsb-service
  strategy:
    dnsTtlSeconds: 1
    splitBrainThresholdSeconds: 30
    type: failover
    primaryGeoTag: cluster1