---
apiVersion: k8gb.absa.oss/v1beta1
kind: Gslb
metadata:
  name: gslb-service
spec:
  resourceRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    matchLabels:
      app: gslb-service
  strategy:
    dnsTtlSeconds: 1
    splitBrainThresholdSeconds: 30
    type: failover
    primaryGeoTag: cluster2